### ISSUE TITLE
第七题的第七小题解答不够到位

### ISSUE THREAD

**Issue by sorcererxw** [lifei6671/interview-go#15]
https://github.com/lifei6671/interview-go/blob/master/question/q007.md#7%E4%B8%8B%E9%9D%A2%E7%9A%84%E7%A8%8B%E5%BA%8F%E8%BF%90%E8%A1%8C%E5%90%8E%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BC%9A%E7%88%86%E5%BC%82%E5%B8%B8

```go
func (p *Project) run(msgchan chan interface{}) {
	for {
		defer p.deferError()
		go p.exec(msgchan)
		time.Sleep(time.Second * 2)
	}
}
```
这一段错误不仅是 `defer p.deferError()` 没有出现在协程内部，而是无节制地在创建协程。虽然通过 `time.Sleep(time.Second * 2)` 限制了频率，但如果以 Main 内 `time.Sleep(time.Second * 100000000000000)` 如此久的等待，迟早也会因为内存占用过大而报错。

**Comment by lifei6671** [comment]
确实有这个问题，协程msgchan没有关闭。

**Comment by jizengguang** [comment]
m := msg.(int) 这句也有问题吧  获取到的是string类型，断言panic。
是不是应该为：
m,ok := msg.(int)
if ok {
 fmt.Println("msg: ", m)
}
