### ISSUE TITLE
q010.md 示例中 锁应该换为 sync.Mutex

### ISSUE THREAD

**Issue by gopherhw** [lifei6671/interview-go#36]
代码中 并没有用sync.RWMutex锁的特性 这样反而会引起歧义，还不如直接用sync.Mutex更清晰

**Comment by YoghurtFree** [comment]
> 代码中 并没有用sync.RWMutex锁的特性 这样反而会引起歧义，还不如直接用sync.Mutex更清晰

q010这个实现就有问题啊，你开多个goroutine去write，会直接panic，锁的问题用sync.RWMutex还是sync.Mutex无伤大雅，当然确实用sync.Mutex更加严谨一点。具体问题请看pull request最新的一条。希望作者也看一下，不合没关系，自己改一下也可以。

**Comment by lifei6671** [comment]
这个地方最早考虑的是在读的时候用读锁，写的时候用写锁。写的不够严谨。

**Comment by gopherhw** [comment]
> > 代码中 并没有用sync.RWMutex锁的特性 这样反而会引起歧义，还不如直接用sync.Mutex更清晰
> 
> q010这个实现就有问题啊，你开多个goroutine去write，会直接panic，锁的问题用sync.RWMutex还是sync.Mutex无伤大雅，当然确实用sync.Mutex更加严谨一点。具体问题请看pull request最新的一条。希望作者也看一下，不合没关系，自己改一下也可以。

赞 👍
