### ISSUE TITLE
007 最后一个问题感觉讲的有问题

### ISSUE THREAD

**Issue by papandadj** [lifei6671/interview-go#5]
在没有函数调用的情况下， for true{}依然会让出执行权。

**Comment by lifei6671** [comment]
你可以测试下。

**Comment by LieLieLiekey** [comment]
> 在没有函数调用的情况下， for true{}依然会让出执行权。

我这里也是让出了，是goroutine版本高的原因吗？

**Comment by lifei6671** [comment]
> > 在没有函数调用的情况下， for true{}依然会让出执行权。
> 
> 我这里也是让出了，是goroutine版本高的原因吗？

在1.14之前的版本是协作式抢占，之后的版本是信号抢占，协作式抢占需要执行函数。信号抢占不需要，是调度器直接让M挂起执行的G。
